services:
  - type: web
    name: eventsphere
    runtime: python
    rootDir: ./eventsphere
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn eventsphere.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DBNAME
        fromDatabase:
          name: eventsphere-db
          property: database
      - key: DBUSER
        fromDatabase:
          name: eventsphere-db
          property: user
      - key: DBPASSWORD
        fromDatabase:
          name: eventsphere-db
          property: password
      - key: DBHOST
        fromDatabase:
          name: eventsphere-db
          property: host
      - key: DBPORT
        fromDatabase:
          name: eventsphere-db
          property: port

databases:
  - name: eventsphere-db
    databaseName: eventsphere
    user: eventsphere
